apiVersion: v1
kind: Service
metadata:
  name: mern-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: mern-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
