apiVersion: v1
kind: Service
metadata:
  name: mern-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: mern-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      targetPort: {{ .Values.frontend.containerPort }}
